apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: speed-ingress
  namespace: speed
spec:
  ingressClassName: nginx
  rules:
    - host: www.speed.com
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: speed-api
              port:
                number: 8080
