# Default values for monitoring 
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

grafana:
  image:
    repository: angelfoxxu/speed-grafana
    tag: 0.0.3
  adminPassword: password
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: prometheus
          type: prometheus
          url: http://prometheus-server
          access: proxy
          isDefault: true
          editable: false
           
