kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: reader-role
rules:
- apiGroups: ["apps"]
  resources: ["statefulsets","services","pods"]
  verbs: ["get", "list", "watch"]
